### ISSUE TITLE
Send request with key combination #suggestion

### ISSUE THREAD

**Issue by ful-stackz** [jeremyvaartjes/ping#10]
As a user, I would like to be able to send the request without moving my hands from the keyboard. It would be nice to send the request with a key combination. For example, if I have the focus on the URL textbox and I just finished typing it would save me time if I could just click `Enter` to send the request. Also, an app-wide key combination like `Ctrl` + `Enter` will also be comfortable.

**Comment by jeremyvaartjes** [comment]
Fixed in the next release
