### ISSUE TITLE
User-Agent Field

### ISSUE THREAD

**Issue by btd1337** [jeremyvaartjes/ping#2]
@jeremyvaartjes First of all, congratulations on your great work.

Is it possible to add this support to your application?

https://developer.github.com/v3/#user-agent-required

![user-agent-message](https://user-images.githubusercontent.com/11943860/48381359-b59fe900-e6c2-11e8-95af-faf5cfb1e502.png)

**Comment by jeremyvaartjes** [comment]
So I was going to implement a table like interface where the user can add their own headers. This would solve this issue. Will add the feature as soon as I can.
