### ISSUE TITLE
View JSON in pretty format

### ISSUE THREAD

**Issue by yeboahnanaosei** [jeremyvaartjes/ping#9]
It will be nice to view returned json in the response body in "pretty format"

**Comment by btd1337** [comment]
This app could to help:

https://appcenter.elementary.io/com.github.fleury08.prettifier/

**Comment by yeboahnanaosei** [comment]
You can take a cue from how Postman does it. By default json response in Postman appear in pretty format. Makes is very easy to read

**Comment by jeremyvaartjes** [comment]
Fixed in the next release
